version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: localhost:5000/untitled_node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db: